name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.9.0
  - xeus-python=0.8.2
  - notebook
  - pip
  - pip:
    - cirq
    - matplotlib
    - pyquil
    - qiskit
    - quantuminspire
